import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillInstagram, 
  AiFillLinkedin, 
  AiFillGithub
} from 'react-icons/ai'
import Image from 'next/image'
import frontpic from '../public/JJ.png'
import ML from '../public/ml3.png'
import game from '../public/arcade2.png'
import faceDet from '../public/face3.png'
import ex1 from '../public/arcade.png'

import { useState } from 'react'

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Justin Joseph Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Justin Joseph</h1>
            <ul className="flex items-center">
              <li className='dark:text-white'>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-teal-500 to-green-500  text-white px-4 py-2 rounded-md ml-8'href='./res.pdf' target={'_blank'}>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-500 font-medium md:text-6xl'>
              Justin Joseph
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-400'>Mechatronics Engineering Student-Athlete at UW</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>
              Hi! My name is Justin and I'm an aspiring Robotics/Software 
              Engineer at the University of Waterloo. I am also a proud member of 
              the Varsity Men's Soccer team! Welcome to my website!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-500 dark:text-white'>
            <AiFillGithub onClick={() => window.open('https://github.com/JustinJoseph03', '_blank')} className='cursor-pointer'/>
            <AiFillLinkedin onClick={() => window.open('https://www.linkedin.com/in/justin-joseph-aa691721a/', '_blank')} className='cursor-pointer'/>
            <AiFillInstagram onClick={() => window.open('https://www.instagram.com/justin.j17/', '_blank')} className='cursor-pointer'/>
          </div>
          <div className='relative mx-auto rounded-full w-80 h-80 mt-10 mb-5 overflow-hidden md:h-96 md:w-96'>
            <Image src={frontpic} layout='fill' objectFit='cover'/>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-teal-500'>Projects and Experience</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              To date I have worked on various projects ranging from 
              <span className='text-teal-500'> AI/Machine Learning </span> to 
              <span className='text-teal-500'> 3D modeling in Solidworks/AutoCAD </span>. I also have 
              professional experience troubleshooting 
              <span className='text-teal-500'> Raspberry Pi OS </span> and varying levels of experience
              with <span className='text-teal-500'> C++, Python, Java/JavaScript, CSS, HTML, React, PLC programming
              and Arduinos</span>.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white' >
            My diligent work ethic and solid time management skills as a 
            student-athlete also make me a unique and valuable
            candidate for your company as I am used to strict schedules
            and working to achieve a common goal as a team.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={ML} width={800} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Machine Learning
              </h3>
              <p className='py-2'>
                self driving car sim capable of...
              </p>
              <h4 className='py-4 text-teal-600'>Includes:</h4>
              <p className='text-gray-800 py-1'>Javascript</p>
              <p className='text-gray-800 py-1'>HTML and CSS</p>
              <p className='text-gray-800 py-1'>Deep learning visualizer for the car's brain</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={faceDet} width={600} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Machine Learning
              </h3>
              <p className='py-2'>
                self driving car sim capable of...
              </p>
              <h4 className='py-4 text-teal-600'>Includes:</h4>
              <p className='text-gray-800 py-1'>Javascript</p>
              <p className='text-gray-800 py-1'>HTML and CSS</p>
              <p className='text-gray-800 py-1'>Deep learning visualizer for the car's brain</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={game} width={800} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Machine Learning
              </h3>
              <p className='py-2'>
                self driving car sim capable of...
              </p>
              <h4 className='py-4 text-teal-600'>Includes:</h4>
              <p className='text-gray-800 py-1'>Javascript</p>
              <p className='text-gray-800 py-1'>HTML and CSS</p>
              <p className='text-gray-800 py-1'>Deep learning visualizer for the car's brain</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-teal-500'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              To date I have worked on various projects ranging from 
              <span className='text-teal-500'> AI/Machine Learning </span> to 
              <span className='text-teal-500'> 3D modeling in Solidworks/AutoCAD </span>. I also have 
              professional experience troubleshooting 
              <span className='text-teal-500'> Raspberry Pi OS </span> and varying levels of experience
              with <span className='text-teal-500'> C++, Python, Java/JavaScript, CSS, HTML, React, PLC programming
              and Arduinos</span>.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
            My diligent work ethic and solid time management skills as a 
            student-athlete also make me a unique and valuable
            candidate for your company as I am used to strict schedules
            and working to achieve a common goal as a team.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg: flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={ex1} 
              className='rounded-lg object-cover' 
              width={'100%'} height={'100%'} 
              layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={ex1} 
              className='rounded-lg object-cover' 
              width={'100%'} 
              height={'100%'} 
              layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={ex1} 
              className='rounded-lg object-cover' 
              width={'100%'} height={'100%'} 
              layout='responsive'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={ex1} 
              className='rounded-lg object-cover' 
              width={'100%'} height={'100%'} 
              layout='responsive'
              />
            </div>
          </div>
        </section>

      </main>

      
    </div>
  )
}
